### ISSUE TITLE
No Drops when Player Kills Pal

### ISSUE THREAD

**Issue by Simpuhl** [JannikBirn/palworld-host-save-fix#3] opened 2024-01-28 04:18 UTC
I only seem to get drops when my Pal kills other pals. If I kill them, I always get nothing.

**Comment by JannikBirn** [comment] 2024-01-28 16:01
I can't recreate the bug with my save file, so it's hard for me to tell what the source of the problem is. Please let me know if you find out anything possibly related to this issue.

**Comment by Simpuhl** [comment] 2024-01-28 16:18
I'll redo it tonight from scratch and see if it's fixed. One thing I do have that's different is the game ignores working pala up to 20 in the config unless you also copy your world Sav file and maybe it's related? Doubt it but maybe... I'm snowboarding today but tonight I'll try

**Comment by Simpuhl** [comment] 2024-01-28 23:31
> I can't recreate the bug with my save file, so it's hard for me to tell what the source of the problem is. Please let me know if you find out anything possibly related to this issue.

Ok, so I am trying the script again but I get this error... I did re-clone it also.

![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/262571/431d4dd9-c147-4e2c-84f6-751781cb92a7)

![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/262571/e993388c-5b47-46b9-a6d8-e4b9cf0331e8)

![image](https://github.com/JannikBirn/palworld-host-save-fix/assets/262571/26ca9a2d-b6e7-4a59-a5db-4f541723a9f9)

All files appear to be there

**Comment by JannikBirn** [comment] 2024-01-28 23:44
Ah, can you try to open the terminal at the folder with the fix-host-save.py script? 
Just do `cd C:\Users\simpu\OneDrive\Documents\GitHub\palworld-host-save-fix`
Please let me know if that will fix this issue. I'll try to fix this bug.

**Comment by JannikBirn** [comment] 2024-01-28 23:49
Just pushed a potential fix, please try again @Simpuhl

**Comment by Simpuhl** [comment] 2024-01-29 06:54
I will try again in the AM. Thanks for continuing to try btw

**Comment by JannikBirn** [comment] 2024-01-29 18:22
Nice, sounds great, I'll close this issue then. Just open a new one if anything comes up.

**Closed by JannikBirn** 2024-01-29 18:22 UTC
Labels: bug

**Comment by divyakanth07** [comment] 2024-01-30 15:17
how do we fix this bug do we redo the script and it should work ?

**Comment by Simpuhl** [comment] 2024-01-30 15:22
I did everything from scratch again, copied over my save, created character, etc.
