### ISSUE TITLE
Gun left click bug

### ISSUE THREAD

**Issue by Simpuhl** [JannikBirn/palworld-host-save-fix#4] opened 2024-01-28 04:19 UTC
Machine gun will occasionally go crazy and shoot all bullets and keep reloading and shooting on a single left click.

It doesn't always happen, but it happens pretty often.

**Comment by JannikBirn** [comment] 2024-01-28 15:24
This Issue will be closed as it is a duplicate of the issue #6 please keep adding new comments to that issue if the new version of the script hasn't fixed the issue for you. A manual guid can be found here: https://github.com/JannikBirn/palworld-host-save-fix/issues/6#issuecomment-1913631932

**Closed by JannikBirn** 2024-01-28 15:24 UTC
Labels: bug, duplicate
